### ISSUE TITLE
Task review, recommendations

### ISSUE THREAD

**Issue by KHajili98** [theMahammad/PragmatechCsharpPoroject#1]
Tasklarda ciddi problem yoxdur. Tasklari kecdiklerinizin esasinda yaz ki sade sheylerle praktikan artsin, ireli movzularda yazmaginda problem yoxdur, amma gelen derslerde bunlari kecesen ve netice etibari ile calish kecdiklerinin tetbiqine fokuslan. **Folder Structure** yaxsi deyil tasklari heftelere uygun qruplashdir. Calish her taska ayri projectde yaz, indiden folder structure prinsipi formalashsin. Sabah bundan boyuk tasklar ishleyende cetinlik cekmeyesen. Hemcinin her taski eledikce gite elave et. Commit message-lari ingilisce yaz ki, verdish halina kecsin.

**Comment by theMahammad** [comment]
Çox sağ ol məsləhətin üçün,sadəcə 3 ildir bu təhsili aldığım üçün sadə yazmağa əlim gəlmədi :(
