### ISSUE TITLE
Folder structure 

### ISSUE THREAD

**Issue by KHajili98** [theMahammad/PragmatechCsharpPoroject#2]
Week01/task1,task2,task3,task4 seklinde olmalidir folder structure. **yeniden diqqet edersen.**

**Comment by theMahammad** [comment]
Yəni tasks içində olmasın week1?

**Comment by KHajili98** [comment]
> Yəni tasks içində olmasın week1?
Tasks/Week__1 bu okaydir. Week_1/Task_1  bu ne ucun lazimdir?. yeqin evvel yaratmisan sonra da yaddan cixibdir

**Comment by theMahammad** [comment]
> > Yəni tasks içində olmasın week1?
> > Tasks/Week__1 bu okaydir. Week_1/Task_1  bu ne ucun lazimdir?. yeqin evvel yaratmisan sonra da yaddan cixibdir

Aha,elə olmuşdu,düzəltdim,çox sağ ol
